### PR TITLE
Ensure change events bubble

### LINKED ISSUE #597: New native events that should bubble don't bubble
E.g. try theme remixing, which is currently broken. It listens to `change` on an ancestor. Changing that to `input` doesn't fix it, but adding `{capture: true}` does, which means the event isn't bubbling.

Indeed, printing out `event.bubbles` prints out `false`.

I believe specifying `bubbles: true` explicitly when dispatching them would fix this.

### PR DESCRIPTION
**Pull request by claviska**
Fixes #597

### CODE REVIEW

File: src/internal/webawesome-element.ts [hunk 1]
```diff
@@ -160,14 +160,18 @@ export default class WebAwesomeElement extends LitElement {
...
-    }
+  relayNativeEvent(event: Event, eventOptions?: EventInit) {
+    event.stopImmediatePropagation();
+
+    this.dispatchEvent(
+      new (event.constructor as typeof Event)(event.type, {
+        ...event,
+        ...eventOptions,
+      }),
+    );
```
Comment (claviska) [inline src/internal/webawesome-element.ts:174]: I kept this as sugar. I don't love how we need to remember to explicitly add bubbles/composed to change events...it feels like a footgun. Perhaps a long term strategy would bake in default for certain event types, but this works in the meantime.

Comment (LeaVerou) [reply src/internal/webawesome-element.ts:174]: Agreed, I think it would be better to encode that here (or anywhere else that is central), i.e. have an object literal with the default `bubbles` state and read it from there. But meanwhile, this works.

**Review by LeaVerou — APPROVED** [review]

**Comment by LeaVerou** [comment]
Merging this in the hopes it fixes #605
